_target_: pfp.backbones.pointnet2.PointNet2Backbone
embed_dim: ${obs_features_dim}
n_points: ${dataset.n_points}
use_group_norm: False
# Optional: customize SA layer configurations
sa_configs:
  - npoints: 1024 # 改为 npoints (复数)
    radius: 0.03
    nsample: 16
    mlp: [32, 32, 64]
    in_channel: 3
  - npoints: 256 # 改为 npoints (复数)
    radius: 0.8
    nsample: 32
    mlp: [64, 64, 128]
    in_channel: 67 # 添加 in_channel 字段（64+3，因为上一层输出64维特征+3维xyz）
  - npoints: null # 改为 npoints (复数)，group_all
    radius: null
    nsample: null
    mlp: [256, 512, 1024]
    in_channel: 131 # 添加 in_channel 字段（256+3，因为上一层输出256维特征+3维xyz）

